name: Parse moon data

on:
  workflow_dispatch:

jobs:
  run-parser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium undetected-chromedriver beautifulsoup4

      - name: Run parser script
        id: parse
        run: |
          # Запускаем скрипт и сохраняем чистый JSON вывод
          JSON_OUTPUT=$(python parse_data.py)
          
          # Проверяем валидность JSON
          if ! jq -e . >/dev/null 2>&1 <<<"$JSON_OUTPUT"; then
            echo "::error::Invalid JSON output"
            exit 1
          fi
          
          # Сохраняем в output и файл
          echo "json_data=$JSON_OUTPUT" >> $GITHUB_OUTPUT
          echo "$JSON_OUTPUT" > moon_data.json
          
          # Логируем первые 200 символов для отладки
          echo "First 200 chars of JSON:"
          echo "$JSON_OUTPUT" | head -c 200

      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: moon-data
          path: moon_data.json

      - name: Show result
        run: |
          echo "Parsed data length: ${#{{ steps.parse.outputs.json_data }}} chars"
          echo "Sample: {{ steps.parse.outputs.json_data | slice(0, 50) }}..."
