name: Parse required data and transfer >> process it

on:
  workflow_dispatch:

jobs:
  run-parser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium undetected-chromedriver beautifulsoup4

      - name: Run parser script
        id: parse
        run: |
          python parse_data.py > output.json
          echo "JSON_DATA=$(cat output.json)" >> $GITHUB_OUTPUT
          cat output.json  # Для проверки в логах

      - name: Save JSON to file
        run: |
          echo '${{ steps.parse.outputs.JSON_DATA }}' > moon_data.json
          echo "Содержимое moon_data.json:"
          cat moon_data.json
